# Generated by Django 4.2.23 on 2025-12-07 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamentorecebido',
            name='metodo',
            field=models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'Pix'), ('CARTÃO', 'Cartão')], default='DINHEIRO', max_length=50),
        ),
        migrations.AlterField(
            model_name='pagamentovenda',
            name='metodo',
            field=models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'Pix'), ('CARTÃO', 'Cartão'), ('PRAZO', 'A Prazo (Fiado)')], default='DINHEIRO', max_length=50),
        ),
    ]
