# Generated by Django 4.2.23 on 2026-01-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_pagamentorecebido_metodo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco_prazo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço a Prazo'),
        ),
        migrations.AddField(
            model_name='produto',
            name='tem_preco_prazo',
            field=models.BooleanField(default=False, verbose_name='Tem Preço a Prazo?'),
        ),
    ]
